### ISSUE TITLE
表情認識テストをしている途中でエラーが発生する

### ISSUE THREAD

**Issue by opera7133** [Chizuchizu/bunkasai_face#5]
**エラー内容**
```
OMP: Info #154: KMP_AFFINITY: Initial OS proc set respected: 0-3
OMP: Info #213: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #276: KMP_AFFINITY: Affinity capable, using global cpuid leaf 11 info
OMP: Info #156: KMP_AFFINITY: 4 available OS procs
OMP: Info #157: KMP_AFFINITY: Uniform topology
OMP: Info #191: KMP_AFFINITY: 1 socket x 2 cores/socket x 2 threads/core (2 total cores)
OMP: Info #215: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #171: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 1 maps to socket 0 core 0 thread 1
OMP: Info #171: KMP_AFFINITY: OS proc 2 maps to socket 0 core 1 thread 0
OMP: Info #171: KMP_AFFINITY: OS proc 3 maps to socket 0 core 1 thread 1
OMP: Info #251: KMP_AFFINITY: pid 15244 tid 11064 thread 0 bound to OS proc set 0
OMP: Info #251: KMP_AFFINITY: pid 15244 tid 14800 thread 1 bound to OS proc set 2
anger: 100.0%
happiness: -0.0%
Dominant emotion: anger

Traceback (most recent call last):
  File "main.py", line 225, in <module>
    app.loop()
  File "main.py", line 146, in loop
    predict, ps = main()
  File "C:\Ws\bunkasai_face\core\face_emotions.py", line 31, in main
    res, ps = model.predict(file)
TypeError: 'NoneType' object is not iterable
```

**スクリーンショット**
![ddl7](https://user-images.githubusercontent.com/39876629/65402505-c7393d80-de09-11e9-8545-38acf7b21211.png)

**環境:**
 - OS: Windows10
 - Python: 3.6.9

**Comment by chizuchizu** [comment]
EmoPyのライブラリのコードの中身は変えましたか？

エラーメッセージでNoneTypeとなっているので多分ライブラリのコードを修正していないように推測できます。

**Comment by opera7133** [comment]
すいません、もう一度確認してみます
